blank_issues_enabled: false
contact_links:
  - name: Security disclosure
    url: https://github.com/broccolirob/rag-hygiene-scanner/security/policy
    about: Please report vulnerabilities privately via SECURITY.md
